#!/bin/sh
cap="$(cat /sys/class/power_supply/BAT0/capacity)"
status="$(cat /sys/class/power_supply/BAT0/status)"
estimated="$(acpi -b | grep -E 'remaining|until' | awk '{print $5}')"
if [ $status = "Charging" ]; then 
   icon=""
       if [ $cap -ge 85 ] ;then
       notify-send "battery $cap"
    fi
fi
if [ $status = "Discharging" ]; then
    icon=""
fi
printf "%s %s (%s)" "$icon" "$cap" "$estimated"
