#!/bin/bash

wifistatus="$(cat /sys/class/net/w*/operstate)"
ethstatus="$(cat /sys/class/net/enp7s0/operstate)"
if [ $wifistatus = "up" ]; then 
    essid="$(nmcli c | sed -n '2{p;q}' | awk '{print $1" "$2}')"
    quality="$(cat /proc/net/wireless |  sed -n '3{p;q}' | awk '{printf "%.0f\n",$3}')"
  #  uspeed="$(speedtest | awk '/Upload/ {print}' | sed 's/Upload/u/')" This I tried for the upload and download speed but it took a lot of time in running, So Commenting them now
  #  dspeed="$(speedtest | awk '/Download/ {print}' | sed 's/Download/d/')"
    icon=""
elif [ $ethstatus = "up" ]; then
    essid="$(nmcli c | sed -n '2{p;q}' | awk '{print $5}')"
    quality=""
    icon=""
elif [ -d /sys/class/net/enp0s* ]; then
    essid="$(nmcli c | sed -n '2{p;q}' | awk '{print $5}')"
    quality=""
    icon=""
else
    essid="Disconnected"
    quality=""
    icon=""
fi
printf "%s %s" "$essid" "$quality"

	
